[package]
name = "mikan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bootx64"
path = "src/main.rs"

[dependencies]
uefi = "0.16"
uefi-services = "0.13"
